name: Action - Python SDK
description: Builds and Publishes Python SDK to PyPI via OIDC

inputs:
  package_name:
    description: Name of the python package
    required: true
  package_version:
    description: Version of the package
    required: true
  # --- INTERNAL PARAMETERS (Visible at the top) ---
  output_dir:
    description: Internal output directory
    default: "./gen/python"
  dist_dir:
    description: Internal distribution directory
    default: "./gen/python/dist/"

runs:
  using: "composite"
  steps:
    - name: Generate Python SDK
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: python
        openapi-file: swagger.json
        command-args: >
          --package-name ${{ inputs.package_name }}
          -o ${{ inputs.output_dir }}
          --additional-properties=packageName=${{ inputs.package_name }},packageVersion=${{ inputs.package_version }}

    - name: Install Build Tools
      shell: bash
      run: pip install build

    - name: Build Package
      shell: bash
      run: |
        cd ${{ inputs.output_dir }}
        python -m build

    - name: Publish to PyPI (OIDC)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ${{ inputs.dist_dir }}

    - name: Upload Python SDK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sdk-python
        path: ${{ inputs.output_dir }}
