name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # 1. PRE-SETUP: Define semantic conditions
  pre-setup:
    runs-on: ubuntu-latest
    outputs:
      is_commit_on_trunk: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    steps:
      - name: Pipeline started
        run: echo "Initializing pipeline for ${{ github.ref_name }} via ${{ github.event_name }}"

  # 2. QA: Run E2E tests
  qa:
    needs: pre-setup
    uses: ./.github/workflows/job-qa.yaml
    secrets: inherit

  # 3. OPENAPI-SDKS: Generate OpenAPI and SDKs (Only on trunk)
  openapi-sdks:
    needs: [pre-setup, qa]
    if: needs.pre-setup.outputs.is_commit_on_trunk == 'true'
    uses: ./.github/workflows/job-openapi-sdks.yaml
    with:
      docker_target: "openapi-spec"

  # 4. DEPLOY: Launch deployment
  deploy:
    needs: [pre-setup, openapi-sdks]
    if: needs.pre-setup.outputs.is_commit_on_trunk == 'true'
    uses: ./.github/workflows/job-deploy.yaml
    secrets: inherit
