name: Job - OpenAPI SDK Generation
on:
  workflow_call:
    inputs:
      docker_target:
        required: true
        type: string
      publish_to_pypi:
        required: false
        type: boolean
        default: false
      version_suffix:
        required: false
        type: string
        default: ""

jobs:
  # 1. ORCHESTRATOR: Decide what needs to be built
  prepare:
    runs-on: ubuntu-latest
    outputs:
      should_build_python: ${{ steps.check-change.outputs.changed }}
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v4
      
      - name: Export Spec from Docker
        run: docker build --target ${{ inputs.docker_target }} --output type=local,dest=. .

      - name: Calculate Spec Hash
        id: spec-hash
        shell: bash
        run: |
          HASH=$(sha256sum swagger.json | cut -d ' ' -f 1)
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"
          echo "Current spec hash: $HASH"

      - name: Restore Last Successful Spec Hash
        id: cache-hash
        uses: actions/cache/restore@v5
        with:
          path: .last_spec_hash
          key: spec-hash-${{ steps.spec-hash.outputs.hash }}

      - name: Check if Spec Changed
        id: check-change
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             echo "changed=true" >> "$GITHUB_OUTPUT"
          elif [ -f .last_spec_hash ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "${{ steps.spec-hash.outputs.hash }}" > .last_spec_hash
          fi

      - name: Save New Spec Hash (Trunk only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && steps.check-change.outputs.changed == 'true' && success()
        uses: actions/cache/save@v5
        with:
          path: .last_spec_hash
          key: spec-hash-${{ steps.spec-hash.outputs.hash }}

  # 2. SPECIALIST: Python
  python-sdk:
    needs: prepare
    if: needs.prepare.outputs.should_build_python == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/job-sdk-python.yaml
    with:
      package_name: "gdariodev-${{ github.event.repository.name }}"
      package_version: "0.0.${{ github.run_number }}${{ inputs.version_suffix }}"
      publish_to_pypi: ${{ inputs.publish_to_pypi }}
      docker_target: ${{ inputs.docker_target }}
